### ISSUE TITLE
Liste med folk som trenger tilgang til bill.sys

### ISSUE THREAD

**Issue by ingceckri** [blindernuka/billett#81]
Kommer!

**Comment by henrist** [comment]
Legg gjerne inn brukernavn fra
https://foreningenbs.no/intern/users

Her er dagens tilgangsliste (til info):
https://github.com/blindernuka/billett/blob/master/app/src/Billett/Auth/Guard.php#L7

**Comment by henrist** [comment]
Fikset i ac94e4b4
